<a href="https://colab.research.google.com/github/lislmaka/DS-ML/blob/main/Numpy_Tutorial_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**
Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object and tools for working with these arrays.
>**NumPy is short for "Numerical Python".**

>**It also has functions for working in domain of:**


>>  1.   linear algebra
>
>>  2.   fourier transform
>
>>  3.   matrices



#### The **array object** in NumPy is called **ndarray**, it provides a lot of supporting functions that make working with ndarray very easy.

# **Why is NumPy Faster Than Lists?**
>**NumPy arrays** are **stored** at **one** continuous **place** in **memory** unlike **lists**, so processes can access and manipulate them very efficiently.

>This **behavior** is called **locality** of **reference** in **computer science**.

>Also **optimized** to **work** with **latest CPU architectures**.

### **Install Numpy**

In [ ]:
!pip install numpy

In [ ]:
import numpy

>NumPy is **usually imported** under the **np alias**.

**alias:** In Python **alias** are an **alternate name** for **referring to the same thing**.

In [2]:
import numpy as np

# **Checking NumPy Version**
The **version string** is stored under **__version__ attribute**.

In [3]:
print(np.__version__)

2.0.2


# **NumPy Creating Arrays**
>NumPy is used to work with arrays.
>> The **array object** in NumPy is called **ndarray**.

>We can create a **NumPy ndarray** object by using the **array() function**.

In [4]:
arr = np.array([12,20,30,40,50,60])

print(arr)

print(type(arr))

[12 20 30 40 50 60]
<class 'numpy.ndarray'>


>**type():** This **built-in Python function** tells us the type of the object passed to it.

> Like in above code it shows that **arr** is **numpy.ndarray** type

# **To create an ndarray**
>We can **pass** a **list**, **tuple** or any **array-like object** into the ```array()``` method, and it will be **converted into an ndarray**

In [5]:
arr =np.array((10,20,30,40,50,60))
print(arr)

[10 20 30 40 50 60]


## **Create an aray within specified range**
```np.arange()``` method can be used to replace ```np.array(range())``` method

In [6]:
# np.arange(start, stop, step)
arr = np.arange(0, 21, 3)
print(arr)
print(type(arr))

[ 0  3  6  9 12 15 18]
<class 'numpy.ndarray'>


## **Create an array of evenly spaced numbers within specified range**
```np.linspace(start, stop, num_of_elements, endpoint=True, retstep=False)``` has 5 parameters:
- ```start```: start number (inclusive)
- ```stop```: end number (inclusive unless ```endpoint``` set to ```False```)
- ```num_of_elements```: number of elements contained in the array
- ```endpoint```: boolean value representing whether the ```stop``` number is inclusive or not
- ```retstep```: boolean value representing whether to return the step size

In [9]:
arr, step_size = np.linspace(0, 10, 2, endpoint=False, retstep=True)
print(arr)
print(arr.size)
print('The step size is ' + str(step_size))

[0. 5.]
2
The step size is 5.0


## **Create an array of random values of given shape**
```np.random.rand()``` method returns values in the range [0,1)

In [10]:
arr = np.random.rand(3,4)
print(arr)

[[0.50168217 0.24522846 0.2978546  0.85631885]
 [0.71924718 0.04543845 0.59072882 0.11894127]
 [0.11948026 0.78803165 0.54975998 0.59598246]]


## **Create an array of zeros of given shape**
- ```np.zeros()```: create array of all zeros in given shape
- ```np.zeros_like()```: create array of all zeros with the same shape and data type as the given input array

In [ ]:
zeros = np.zeros((2,3))
print(zeros)

## **Create an array of ones of given shape**
- ```np.ones()```: create array of all ones in given shape
- ```np.ones_like()```: create array of all ones with the same shape and data type as the given input array

In [ ]:
ones = np.ones((3,2))
print(ones)

In [ ]:
arr = [[1,2,3], [4,5,6]]
ones = np.ones_like(arr)
print(ones)
print('Data Type: ' + str(ones.dtype))

## **Create an empty array of given shape**
- ```np.empty()```: create array of empty values in given shape
- ```np.empty_like()```: create array of empty values with the same shape and data type as the given input array

Notice that the initial values are not necessarily set to zeroes.

They are just some garbage values in random memory addresses.

In [ ]:
empty = np.empty((2,2))
print(empty)
print(empty.dtype)

In [ ]:
newarr = np.array([[10,20,30], [40,50,60]], dtype=np.int64)
empty = np.empty_like(newarr)
print(empty)
print('Data Type: ' + str(empty.dtype))

## **Create an array of constant values of given shape**  
- ```np.full()```: create array of constant values in given shape
- ```np.full_like()```: create array of constant values with the same shape and data type as the given input array

In [ ]:
full = np.full((4,4), 4)
print(full)

In [ ]:
arr = np.array([[1,2], [3,4]], dtype=np.float64)
full = np.full_like(arr, 5)
print(full)
print('Data Type: ' + str(full.dtype))

## **Create an array in a repetitive manner**
- ```np.repeat(iterable, reps, axis=None)```: repeat each element by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions
    - ```axis```: which axis to repeat along, default is ```None``` which will flatten the input array and then repeat
- ```np.tile(iterable ,reps)```: repeat the whole array by n times
    - ```iterable```: input array
    - ```reps```: number of repetitions, it can be a tuple to represent repetitions along x-axis and y-axis

In [ ]:
# No axis specified, then flatten the input array first and repeat
# Data Augemnation

arr = [[0, 1, 2], [3, 4, 5]]

print(np.repeat(arr, 4))

In [ ]:
# An example of repeating along x-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=0)) # row

In [ ]:
# An example of repeating along y-axis
arr = [[0, 1, 2], [3, 4, 5]]
print(np.repeat(arr, 3, axis=1))

In [ ]:
# Repeat along specified axes
print(np.tile(arr, (2,2)))

## **Create an identity matrix of given size**
- ```np.eye(size, k=0)```: create an identity matrix of given size
    - ```size```: the size of the identity matrix
    - ```k```: the diagonal offset
- ```np.identity()```: same as ```np.eye()``` but does not carry parameters

In [ ]:
identity_matrix = np.eye(4)
print(identity_matrix)
print(type(identity_matrix))

In [ ]:
# An example of diagonal offset
identity_matrix = np.eye(5, k=1) # default k = 0
print(identity_matrix)

In [ ]:
identity_matrix = np.identity(5)
print(identity_matrix)
print(type(identity_matrix))

## **Create an array with given values on the diagonal**

In [ ]:
arr = np.random.rand(5,5)
print(arr)

### **Extract values on the diagonal**


In [ ]:
print('Values on the diagonal: ' + str(np.diag(arr)))

### **Not necessarily to be a square matrix**

In [ ]:
arr = np.random.rand(5,3)
print(arr)
# Extract values on the diagonal
print('Values on the diagonal: ' + str(np.diag(arr)))

### **Create a matrix given values on the diagonal**
> All non-diagonal values set to zeros

In [ ]:

arr = np.diag([1,2,3,4,5,6])
print(arr)

# **Dimensions in Arrays**
A **dimension** in arrays is **one level** of **array depth** (nested arrays).

**Nested array:** are arrays that **have arrays as their elements.**

# **0-D Arrays**
>**0-D arrays**, **,or Scalars**: are the **elements** in an array.
>>**Each value in an array is a 0-D array.**

In [ ]:
#create 0-D array with value '10'

arr=np.array('10')
print(arr)

# **1-D Arrays**
>An **array** that has **0-D arrays** as its **elements** is called **uni-dimensional** or **1-D array**.

>>These are the **most common** and **basic** arrays.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

# **2-D Arrays**
>An **array** that has **1-D arrays** as its **elements** is called a **2-D array**.

>>These are often **used** to **represent matrix** or **2nd order tensors**.

## **NumPy** has a whole **sub module** dedicated towards **matrix operations** called numpy.mat

In [ ]:
arr= np.array([[10,20,30],[40,50,60]])
print(arr)

# **3-D arrays**
>An **array** that has **2-D arrays** (**matrices**) as its **elements** is called **3-D array.**

>>These are often used to **represent** a **3rd order tensor.**

In [ ]:
arr =np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,60]]])
print(arr)

# **Check Number of Dimensions?**
NumPy Arrays provides the **ndim** **attribute** that **returns** an **integer** that tells us how many **dimensions** the array have.

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(f"Number of dimensions in Array is :" ,a.ndim)
print(f"Number of dimensions in Array is :" ,b.ndim)
print(f"Number of dimensions in Array is :" ,c.ndim)
print(f"Number of dimensions in Array is :" ,d.ndim)

# **Higher Dimensional Arrays**
An **array** can have **any number of dimensions**.

>When the array is created, **you can define** the **number** of **dimensions** by using the **ndmin** argument.

In [ ]:
arr = np.array([10,20,30,40,50], ndmin=5)

print(arr)

print(f"Number of dimensions in Array is :", arr.ndim)

# **Inspect general information of an array**

In [ ]:
print(np.info(arr))

# **Data Types in NumPy**
**NumPy** has some **extra data types**, and **refer** to **data types** with **one** **character**, like **i** for **integers**, **u** for **unsigned integers** etc.



*   **i** - integer
*   **b** - boolean

*   **u** - unsigned integer
*   **f** - float

*   **c** - complex float
*   **m** - timedelta

*   **M** - datetime
*   **O** - object

*   **S** - string
*   **U** - unicode string
*   **V** - fixed chunk of memory for other type ( void )




# **Checking the Data Type of an Array**

The **NumPy array object** has a property called **dtype** that **returns** the **data** **type** of the array

In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

# **Creating Arrays With a Defined Data Type**
**array()** function **can** **take** an **optional argument** ,**(dtype)** that allows us to **define** the **expected** **data type** of the array **elements**

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)  #the data will be converted to string

For **i** , **u** , **f**, **S** and **U** we can **define** **size** as well.

>>Create an array with data type **4 bytes integer**

In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

>>Create an array with data type **complex64**


In [ ]:
arr = np.array([[1,2], [3,4],[5,6]], dtype=np.complex64)
print(arr)
print()

# **What if a Value Can Not Be Converted?**
If a type is given in which **elements** **can't be casted** then NumPy **will raise a ValueError.**

## **ValueError**: In Python ValueError is raised when the **type of passed argument** to a **function** is **unexpected/incorrect.**

In [ ]:
#arr = np.array(['a', '2', '3'], dtype='i') #we have a string so we sill get error

# **Converting Data Type on Existing Arrays**

### The best way to **change the data type** of an **existing array**, is to make a **copy of the array** with the **astype()** method.

The **astype()** function **creates a copy of the array** and allows you to **specify** the **data type** as a **parameter**.

>The **data type** can be **specified using** a **string**, like **'f' for float**, **'i' for integer** etc.
>> Or you can **use** the **data type** **directly** like **float** for **float** and **int** for **integer**.

In [ ]:
arr=np.array((1.2,20.2 ,30.3))
print(arr)
print(arr.dtype)



arr2=arr.astype("i")
print(arr2)
print(arr2.dtype)

In [ ]:
arr=np.array((1.2,20.2 ,30.3))
print(arr)
print(arr.dtype)



arr2=arr.astype(int)
print(arr2)
print(arr2.dtype)

In [ ]:
arr=np.array((1.2,20.2 ,0.0))
print(arr)
print(arr.dtype)



arr2=arr.astype("bool")
print(arr2)
print(arr2.dtype)

#  **NumPy Array Indexing**
## **Access Array Elements:**

>Array indexing is the same as accessing an array element.

>You can access an array element by referring to its index number.

>The indexes in NumPy arrays **start with 0**, meaning that the **first element **has index **0**, and the **second** has index **1** etc.

In [ ]:
#Access first element

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[0])

In [ ]:
#Access second element

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[1])

In [ ]:
#Get third and fourth elements from the following array and add them.

arr= np.array([10,20,30,40,50,60,70,80,90,100])

print(arr[2]+arr[3])

## **Access 2-D Arrays**
To access elements from 2-D arrays we can use **comma separated integers** representing **the dimension** and the **index of the element.**

>**dimension index also starts from 0**

In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"First element from first Dimension {arr[0,0]}")

In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"First element from second Dimension {arr[1,0]}")

## **Access 3-D Arrays**
To access elements from 3-D arrays we can use **comma separated integers **representing the **dimensions** and the **index of the element.**

In [ ]:
arr = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,200,300]]])

print(arr)

In [ ]:
#Access the third element of the second array of the first array:
print(arr[0,1,2])

## **Explanation**
**The first number represents the first dimension, which contains two arrays:**

     [ [ 10,20,30 ] , [ 40,50,60] ]

**and:**

    [ [ 70,80,90 ] , [ 100,200,300 ] ]

**Since we selected 0, we are left with the first array:**

    [ [ 10,20,30 ] , [ 40,50,60] ]


**The second number represents the second dimension, which also contains two arrays:**


    [ 10,20,30 ]

**and:**

    [ 40,50,60]

**Since we selected 1, we are left with the second array:**

    [ 40,50,60]

**The third number represents the third dimension (element) , which contains three values:**

    40

    50

    60

**Since we selected 2, we end up with the third value:**

    60

## **Negative Indexing**

>Use negative indexing to access an array from the end.

In [ ]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(f"Last element from first Dimension {arr[0,-1]}")

# **NumPy Array Slicing**

**Slicing in python means taking elements from one given index to another given index.**

We pass slice instead of index like this:

    [start:end]

We can also define the step, like this:

    [start:end:step]

If we **don't** pass **start** its considered **0**

If we **don't** pass **end** its considered **length** of array **in that dimension**

If we **don't** pass **step** its considered **1**

In [ ]:
#Slice elements from index 1 to index 5 from the following array

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:1])

> **Note:** The result **includes** the **start** index, but **excludes** the **end** index.

In [ ]:
#Slice elements from index 4 to the end of the array:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4::1])

In [ ]:
#Slice elements from the beginning to index 4 (not included):

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4:1])

# **Negative Slicing**
**Use the minus operator to refer to an index from the end**

In [ ]:
#Slice from the index 3 from the end to index 1 from the end

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

# **Slicing 2-D Arrays**


In [ ]:
#From the second element, slice elements from index 1 to index 4 (not included)

arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(arr[1,1:4])

In [ ]:
#From both elements, return index 2:

arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(arr[0:2,2])

In [ ]:
#From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print(arr[0:2,1:4])

# **NumPy Array Copy vs View**

## **The Difference Between Copy and View**

**The main difference** between a copy and a view of an array is that the **copy is a new array**, and the **view is just a view of the original array.**

>The **copy owns the data** and **any changes made to the copy** will **not affect original array**, and **any changes made to the original** array will **not affect the copy.**

>The **view does not own the data** and **any changes made to the view** will **affect the original array**, and **any changes made to the original** array will **affect the view**.

## **Copy**
Make a copy, change the original array, and display both arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(f"Arr Original Before{arr}")

x = arr.copy()
print(f"X Copy Before {x}")

arr[0] = 42
print(f"Arr Original After{arr}")

print(f"X Copy After {x}")   #The copy SHOULD NOT be affected by the changes made to the original array.

## **View**

Make a view, change the original array, and display both arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(f"Arr Original Before{arr}")

x = arr.view()
print(f"X View Before {x}")

arr[0] = 42
print(f"Arr Original After{arr}")

print(f"X View After {x}")    #The view SHOULD be affected by the changes made to the original array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(f"Arr Original Before{arr}")

x = arr.view()
print(f"X View Before {x}")

x[0] = 42
print(f"X View After{arr}")

print(f"Arr Original After {x}")    #The original array SHOULD be affected by the changes made to the view.

# **Check if Array Owns its Data**

* **Copies owns the data**
* **Views does not own the data**

Every NumPy array has the attribute **base** that returns **None** if the array **owns the data.**

Otherwise, the **base**  attribute **refers to the original object**.

In [ ]:
#Print the value of the base attribute to check if an array owns it's data or not:


arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(f"base attribute for Copy is :{x.base}")
print(f"base attribute for View is :{y.base}")

# **NumPy Array Shape**
The shape of an array is the number of elements in each dimension.

NumPy arrays have an **attribute** called **shape** that **returns** a **tuple** with **each index** having the **number** of **corresponding** **elements**.

In [ ]:
#Print the shape of a 2-D array

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)  #OUTPUT 2 >>> Two elements in first dimension , 4 >>> Four elements in second dimension

In [ ]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1,2,3,4] , ndmin=5)


print('shape of array :', arr.shape)  #arr has 5 dimensions, in each dimension there is only one element except for the last dimension has 4 elements ([1, 2, 3, 4]).

# **NumPy Array Reshaping**

> By reshaping we can **add** or **remove** **dimensions** or **change** **number** of elements in **each** **dimension**.

## **Reshape From 1-D to 2-D**
the outermost dimension will have 2 arrays, each with 6 elements:

In [ ]:
#Convert the following 1-D array with 12 elements into a 2-D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 6)

print(newarr)

## **Reshape From 1-D to 3-D**
The outermost dimension will have 2 arrays that contains 2 arrays, each with 3 elements:

In [ ]:
#Convert the following 1-D array with 12 elements into a 3-D array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2,2,3)

print(newarr)

# **Can We Reshape Into any Shape?**
>Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an **8 elements 1D array** into **4 elements in 2 rows 2D array **but we **cannot reshape it into a 3 elements 3 rows 2D array** as that **would require 3x3 = 9 elements.**

## **Check if the returned array is a copy or a view**

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)   #The example returns the original array, so it is a view

# **Unknown Dimension**
**You are allowed to have one "unknown" dimension.**

Meaning that **you do not have to specify an exact number for one of the dimensions** in the reshape method.

**Pass -1 as the value**, and NumPy will **calculate** this number for you.

In [ ]:
#Convert 1D array with 8 elements to 3D array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr=arr.reshape(2,2,-1)

print(newarr)

In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr=arr.reshape(-1,2,2)

print(newarr)

In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr=arr.reshape(2,-1,2)

print(newarr)

# **Flattening the arrays**

## **Flattening array means converting a multidimensional array into a 1D array.**

We can use **reshape(-1)** to do this.

In [ ]:
arr = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,200,300]]])
print(arr)


newarr = arr.reshape(-1)
print(newarr)